version: '3.8'
services:
  movies:
    image: deepagashe/mmovie:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image:  deepagashe/train:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  recharge:
    image:  deepagashe/recharge:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  dth:
    image:  deepagashe/dth:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
